name = "ifmahoushoujo"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ifmahoushoujo"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.preview]
name = "ifmahoushoujo-preview"
compatibility_date = "2024-01-01" 
compatibility_flags = ["nodejs_compat"]